#!/usr/bin/env node
/**
 * cli.ts — repomem-map command line.
 *
 *   repomem-map [serve] [--root <dir>]   start the MCP server over stdio (default)
 *   repomem-map --help                   usage
 *
 * Generation of summaries is driven by the invoking agent through the MCP
 * tools (request_summaries / save_summary), not by a CLI subcommand.
 */

import path from "node:path";
import { fileURLToPath } from "node:url";
import { startServer } from "./index.js";
import { launchViewer } from "./web/launch.js";

export interface ParsedArgs {
  command: "serve" | "help" | "graph";
  rootFlag: string | undefined;
  portFlag: number | undefined;
}

function flag(argv: string[], name: string): string | undefined {
  const i = argv.indexOf(name);
  if (i !== -1 && i + 1 < argv.length) return argv[i + 1];
  return undefined;
}

function numberFlag(argv: string[], name: string): number | undefined {
  const raw = flag(argv, name);
  if (raw === undefined) return undefined;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) ? n : undefined;
}

/** Parse argv into a command and flags. Defaults to `serve`. */
export function parseArgs(argv: string[]): ParsedArgs {
  const first = argv[0];
  if (first === "--help" || first === "-h" || first === "help") {
    return { command: "help", rootFlag: undefined, portFlag: undefined };
  }
  if (first === "graph") {
    return {
      command: "graph",
      rootFlag: flag(argv, "--root"),
      portFlag: numberFlag(argv, "--port"),
    };
  }
  return { command: "serve", rootFlag: flag(argv, "--root"), portFlag: undefined };
}

function err(message: string): void {
  process.stderr.write(message + "\n");
}

function usage(): void {
  err(
    [
      "repomem-map — structure map for repomem",
      "",
      "Usage:",
      "  repomem-map [serve] [--root <dir>]            Start the MCP server over stdio (default)",
      "  repomem-map graph [--root <dir>] [--port N]   Open the dependency graph web viewer",
      "  repomem-map --help                            Show this help",
      "",
      "Summaries are generated by the invoking agent via the MCP tools",
      "request_summaries and save_summary. The dependency graph and viewer work",
      "without summaries. See the README.",
    ].join("\n"),
  );
}

/** Run the CLI. Returns a process exit code. */
export async function run(argv: string[] = process.argv.slice(2)): Promise<number> {
  const { command, rootFlag, portFlag } = parseArgs(argv);
  if (command === "help") {
    usage();
    return 0;
  }
  const root = rootFlag ? path.resolve(rootFlag) : process.cwd();
  if (command === "graph") {
    const handle = await launchViewer({ root, port: portFlag, openBrowser: true });
    err(`[repomem-map] dependency graph viewer: ${handle.url}`);
    err("[repomem-map] press Ctrl+C to stop.");
    // Keep the process alive while the server runs.
    await new Promise<void>(() => {});
    return 0;
  }
  await startServer(root);
  return 0;
}

// Only auto-run when invoked directly (not when imported by tests).
const invokedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  run()
    .then((code) => {
      if (code !== 0) process.exit(code);
    })
    .catch((e: unknown) => {
      err(`fatal: ${(e as Error).message}`);
      process.exit(1);
    });
}
