#!/usr/bin/env node
/**
 * cli.ts — repomem-map command line.
 *
 *   repomem-map [serve] [--root <dir>]   start the MCP server over stdio (default)
 *   repomem-map --help                   usage
 *
 * Generation of summaries is driven by the invoking agent through the MCP
 * tools (request_summaries / save_summary), not by a CLI subcommand.
 */

import path from "node:path";
import { fileURLToPath } from "node:url";
import { startServer } from "./index.js";

export interface ParsedArgs {
  command: "serve" | "help";
  rootFlag: string | undefined;
}

function flag(argv: string[], name: string): string | undefined {
  const i = argv.indexOf(name);
  if (i !== -1 && i + 1 < argv.length) return argv[i + 1];
  return undefined;
}

/** Parse argv into a command and flags. Defaults to `serve`. */
export function parseArgs(argv: string[]): ParsedArgs {
  const first = argv[0];
  if (first === "--help" || first === "-h" || first === "help") {
    return { command: "help", rootFlag: undefined };
  }
  return { command: "serve", rootFlag: flag(argv, "--root") };
}

function err(message: string): void {
  process.stderr.write(message + "\n");
}

function usage(): void {
  err(
    [
      "repomem-map — structure map for repomem",
      "",
      "Usage:",
      "  repomem-map [serve] [--root <dir>]   Start the MCP server over stdio (default)",
      "  repomem-map --help                   Show this help",
      "",
      "Summaries are generated by the invoking agent via the MCP tools",
      "request_summaries and save_summary. See the README.",
    ].join("\n"),
  );
}

/** Run the CLI. Returns a process exit code. */
export async function run(argv: string[] = process.argv.slice(2)): Promise<number> {
  const { command, rootFlag } = parseArgs(argv);
  if (command === "help") {
    usage();
    return 0;
  }
  const root = rootFlag ? path.resolve(rootFlag) : process.cwd();
  await startServer(root);
  return 0;
}

// Only auto-run when invoked directly (not when imported by tests).
const invokedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  run()
    .then((code) => {
      if (code !== 0) process.exit(code);
    })
    .catch((e: unknown) => {
      err(`fatal: ${(e as Error).message}`);
      process.exit(1);
    });
}
